### ISSUE TITLE
在一个普通的ViewContoller里弹出UIImagePickerController不走代理

### ISSUE THREAD

**Issue by applebest** [308823810/AnimationTransitionDemo#1]
![image](https://user-images.githubusercontent.com/16376401/53144067-a7bd0680-35d5-11e9-831f-658e96a3741d.png)
将UIViewController+SS_AnimationTransition.m   runTime拦截viewWillAppear处注释可执行代理

**Comment by applebest** [comment]
[CLTVideoRecording-master 2.zip](https://github.com/308823810/SS_AnimationTransition/files/2887686/CLTVideoRecording-master.2.zip)
可参照此工程测试

**Comment by applebest** [comment]
@308823810

**Comment by JerryDream007** [comment]
问题已修复，更新到最新版本即可
